# Generated by Django 4.0 on 2021-12-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planmodel_transactionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
                ('interval', models.CharField(blank=True, help_text='Payment frequency. Only required if this is a subscription plan.', max_length=11, null=True)),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flw_transactions', to='app.plan'),
        ),
        migrations.DeleteModel(
            name='PlanModel',
        ),
    ]
